### ISSUE TITLE
Cannot build on Mac OS X 10.9.2

### ISSUE THREAD

**Issue by schmurfy** [mobile-shell/mosh#543]
There is one issue about this but it was closed, I still get the error though, am I the only one ?

Here is the relevant configure part:

```
checking util.h usability... no
checking util.h presence... no
[...]
﻿﻿checking whether forkpty is declared... no
checking for forkpty in -lutil... yes
```

and later:

```
mosh-server.cc:426:17: error: use of undeclared identifier 'forkpty'
pid_t child = forkpty( &master, NULL, &child_termios, &window_size );
              ^
```

I tried on master and the same happen, where this file should be located ?
I have developer tools installed and I have no problem compiling something else, if I do a `man forkpty` I also correctly get the manpage for it.
