### PR TITLE
mosh.pl: Fix the error message if getaddrinfo is missing

### LINKED ISSUE #935: Compiled and installed sucessfully, but failed to execute mosh
- CentOS6.5-32bit

I downloaded mosh-1.3.2.tar.gz file from page https://mosh.org/#getting and followed the instructions to compile and install mosh from the source code. The compilation and installation works smoothly, but when I tried to execute the mosh binary file like `mosh --help` or `mosh`, error messages occurred to me:

    Bareword "AI_NUMERICHOST" not allowed while "strict subs" in use at /usr/bin/mosh line 489.
    Bareword "AI_CANONNAME" not allowed while "strict subs" in use at /usr/bin/mosh line 498.
    Bareword "NI_NUMERICHOST" not allowed while "strict subs" in use at /usr/bin/mosh line 336.
    Bareword "NI_NUMERICHOST" not allowed while "strict subs" in use at /usr/bin/mosh line 261.
    Execution of /usr/bin/mosh aborted due to compilation errors.

### PR DESCRIPTION
**Pull request by andersk**
Fixes #935.

### CODE REVIEW

**Comment by eminence** [comment]
:pizza:  confirmed this is working on my old perl 5.8.8 machines at work

**Comment by cgull** [comment]
Confirmed working (well, erroring correctly) in my minimal Centos 6.5 VM.  Thanks!
