### ISSUE TITLE
Mosh fails to build on OS X 10.9 - undeclared identifier 'forkpty'

### ISSUE THREAD

**Issue by brettdh** [mobile-shell/mosh#517]
Either via `brew install mosh` or by building from the 1.2.4 tarball:

```
mosh-server.cc:426:17: error: use of undeclared identifier 'forkpty'
  pid_t child = forkpty( &master, NULL, &child_termios, &window_size );
```

Seems related to other libutil.h/util.h issues; `man forkpty` shows `util.h` on my system.
