### ISSUE TITLE
Can’t build on Amazon linux

### ISSUE THREAD

**Issue by ab-c-d** [mobile-shell/mosh#1040]
I tried to build from the source following the instruction for CentOS, but `make` fails with 
```
userinput.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
```
All the dependencies were included, can somebody give instructions on how to build it?

**Comment by eminence** [comment]
Hi, can you let us know what version of CentOS and exactly what dependencies you installed?  Specifically, what protobuf packages?   What's the output of:

    rpm -qa |grep protobuf

**Comment by ab-c-d** [comment]
Now I was somehow able to build it after deleting the pre-installed protobuf and building it from the source. I noticed that using protobuf >=3.8 make compilation of mosh fails, but it works with 3.7.1.
Executing that command prints: `protobuf-2.5.0-8.amzn2.0.2.x86_64`. Thank you for your reply!

**Comment by eminence** [comment]
mosh should work with protobuf 2.5, but since it sounds like your specific problem is solved, I'm going to close this issue.  Thanks!
