### ISSUE TITLE
mosh fails to build on Mac OS X 10.4

### ISSUE THREAD

**Issue by mistydemeo** [mobile-shell/mosh#438]
When building `src/util/pty_compat.cc` on Mac OS X 10.4, the compiler throws the following error:

```
pty_compat.cc: In function 'pid_t my_forkpty(int*, char*, const termios*, const winsize*)':
pty_compat.cc:96: error: 'I_PUSH' was not declared in this scope
```

Looks to come from this section in an `ioctl()` call:

``` c++
#ifndef _AIX
  if ( ioctl(slave, I_PUSH, "ptem") < 0 ||
       ioctl(slave, I_PUSH, "ldterm") < 0 ) {
    perror( "ioctl(I_PUSH)" );
    close( slave );
    close( master );
    return -1;
  }
#endif
```

I'm building on Mac OS X 10.4.11.

**Comment by ahihi** [comment]
I got it to build with a couple of patches:
https://github.com/ahihi/tigerbrew/commit/5ff3f606f2316ba18782f4be838a82063fa40495
https://github.com/ahihi/tigerbrew/commit/a0903889b5c55ba71d5038cfd1de07c89fef613c

Only tested on my iMac G4 with 10.4.11. :)

**Comment by achernya** [comment]
I think the underlying fix in #437 makes this obsolete.
